export const initialState = {
  posts: {
    data: {},
    loading: {
      active: false,
      error: false,
    },
  },
  pros: [
    {
      id: 1,
      name: 'Johnny Zamulony',
      type: 'musician',
      instrument: 'drums',
      genre: 'rock',
      email: 'johnny@zamulony.com',
      rating: '4.5',
      featured: true,
      price: {
        basic: '200 PLN',
        standard: '400 PLN',
        premium: '600 PLN',
      },
      image: '../assets/images/pro-001.jpg',
      decription:
      'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy.',
    },
    {
      id: 2,
      name: 'Samanta Foxxx',
      type: 'musician',
      instrument: 'singer',
      genre: 'pop',
      email: 'samanta@foxxx.com',
      rating: '2.5',
      featured: false,
      price: {
        basic: '100 PLN',
        standard: '300 PLN',
        premium: '500 PLN',
      },
      image: '../assets/images/pro-002.jpg',
      decription:
      'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy.',
    },
    {
      id: 3,
      name: 'Mateusz Wajchę-Przełóż',
      type: 'musician',
      instrument: 'guitar',
      genre: 'death metal',
      email: 'mateusz@wajcha.com',
      rating: '1.5',
      featured: false,
      price: {
        basic: '500 PLN',
        standard: '700 PLN',
        premium: '1200 PLN',
      },
      image: '../assets/images/pro-003.jpg',
      decription:
      'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy.',
    },
    {
      id: 4,
      name: 'Tadek Niejadek',
      type: 'musician',
      instrument: 'guitar',
      genre: 'folk',
      email: 'tadek@niejadek.com',
      rating: '1.5',
      featured: false,
      price: {
        basic: '50 PLN',
        standard: '700 PLN',
        premium: '200 PLN',
      },
      image: '../assets/images/pro-004.jpg',
      decription:
      'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy.',
    },
    {
      id: 5,
      name: 'Antonio Macierewicz',
      type: 'musician',
      instrument: 'bass',
      genre: 'progressive',
      email: 'anthony@macierewicz.gov.pl',
      rating: '0.0',
      featured: false,
      price: {
        basic: '10 PLN',
        standard: '20 PLN',
        premium: '30 PLN',
      },
      image: '../assets/images/pro-005.jpg',
      decription:
      'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy.',
    },
    {
      id: 6,
      name: 'Scooby Dooby Doo',
      type: 'musician',
      instrument: 'DJ',
      genre: 'house',
      email: 'scooby@dooby.com',
      rating: '0.0',
      featured: true,
      price: {
        basic: '300 PLN',
        standard: '500 PLN',
        premium: '700 PLN',
      },
      image: '../assets/images/pro-006.jpg',
      decription:
      'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy.',
    },
    {
      id: 7,
      name: 'Johnny Martyniuk',
      type: 'musician',
      instrument: 'guitar',
      genre: 'disco-polo',
      email: 'johnny@martyniuk.com',
      rating: '5.0',
      featured: true,
      price: {
        basic: '50000 PLN',
        standard: '70000 PLN',
        premium: '90000 PLN',
      },
      image: '../assets/images/pro-007.jpg',
      decription:
      'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy.',
    },
    {
      id: 8,
      name: 'Sławomir Kloc',
      type: 'musician',
      instrument: 'piano',
      genre: 'jazz',
      email: 'slawomir@kloc.com',
      rating: '3.5',
      featured: true,
      price: {
        basic: '250 PLN',
        standard: '350 PLN',
        premium: '450 PLN',
      },
      image: '../assets/images/pro-008.jpg',
      decription:
      'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy.',
    },
    {
      id: 9,
      name: 'Arkadiusz Trąba',
      type: 'musician',
      instrument: 'saxophone',
      genre: 'funk',
      email: 'arkadiusz@traba.com',
      rating: '4.5',
      featured: false,
      price: {
        basic: '350 PLN',
        standard: '550 PLN',
        premium: '650 PLN',
      },
      image: '../assets/images/pro-009.jpg',
      decription:
      'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy.',
    },
    {
      id: 10,
      name: 'Dżesika Grapelli',
      type: 'musician',
      instrument: 'violin',
      genre: 'classical',
      email: 'jessica@grapelli.com',
      rating: '4.5',
      featured: false,
      price: {
        basic: '550 PLN',
        standard: '750 PLN',
        premium: '950 PLN',
      },
      image: '../assets/images/pro-010.jpg',
      decription:
      'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy.',
    },
  ],
};
